apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: nginx
spec:
  containers:
  - name: webserver
    image: nginx
  - name: sidecar
    image: prom/node-exporter
    ports:
      - containerPort: 9100
        name: metrics
      # Optional: configure arguments to set metrics options
    args:
      - "--path.rootfs=/host"
---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  labels:
    app: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: backend-pod
      labels:
        app: redis
    spec:
      containers:
      - name: backend
        image: redis

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    env: challenge
spec:
  selector:
    matchLabels:
      env: challenge
  replicas: 5
  template:
    metadata:
      name: proxy-pod
      labels:
        env: challenge
    spec:
      containers:
      - name: proxy
        image: httpd
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    env: challenge
spec:
  type: NodePort
  selector:
    env: challenge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
